language: c

os: linux
dist: trusty
sudo: required

matrix:
      include:
        - addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
                - gfortran-7
                - numactl
                - libnuma-dev
          env:
             - C_COMPILER="gcc-7"
             - CXX_COMPILER="g++-7"
             - FORTRAN_COMPILER="gfortran-7"

        - addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-8
                - gfortran-8
                - numactl
                - libnuma-dev
          env:
             - C_COMPILER="gcc-8"
             - CXX_COMPILER="g++-8"
             - FORTRAN_COMPILER="gfortran-8"

before_install:
    - export CC="${C_COMPILER}"
    - export CXX="${CXX_COMPILER}"
    - export FC="${FORTRAN_COMPILER}"

install:
    - git clone https://github.com/jemalloc/jemalloc.git
    - cd jemalloc
    - ./autogen.sh
    - mkdir build
    - cd build
    - ../configure --prefix=$(pwd) --with-jemalloc-prefix=je_
    - make -j $(nproc --all)
    - make -j $(nproc --all) -i install
    - export JEPATH=$(pwd)
    - cd ../..

script:
    - make
    - make fortran
    - make -C test
    - numactl --hardware
    - export LD_LIBRARY_PATH=$(pwd):${JEPATH}/lib
    - find test -type f -executable -exec echo "Running {}" \; -exec {} \;
