language: c

os: linux
dist: trusty
sudo: required

# cache dependencies build so they don't have to be built every time
cache:
      directories:
        - ${TRAVIS_BUILD_DIR}/.local

matrix:
      include:
        - addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
                - gfortran-7
                - wget
          env:
             - C_COMPILER="gcc-7"
             - CXX_COMPILER="g++-7"
             - FORTRAN_COMPILER="gfortran-7"

        - addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-8
                - gfortran-8
                - wget
          env:
             - C_COMPILER="gcc-8"
             - CXX_COMPILER="g++-8"
             - FORTRAN_COMPILER="gfortran-8"

before_install:
    - export CC="${C_COMPILER}"
    - export CXX="${CXX_COMPILER}"
    - export FC="${FORTRAN_COMPILER}"

install:
    # Install Spack
    - git clone https://github.com/spack/spack.git
    - cd spack
    - . share/spack/setup-env.sh

script:
    # build and test SICM with Spack
    - spack install --test=root sicm-low
